---
title: "GRAFICAS"
format: html
editor: visual
---

## \## pkgs

```{r}
#| message: false
library(tidyverse)
library(fpp3)
library(plotly)
library(patchwork)
library(tidyquant)
```

```{r}
?aus_accommodation
aus_accommodation
```

```{r}
tasmania <- aus_accommodation |> 
  filter(State == "Tasmania") |> 
  #select(Date, Takings, Occupancy) opción 1
  #select(Date, Takings:Occupancy) opción 2
  select(-c(State, CPI)) |>  #opción 3
  mutate(
    "Año unión  N°1  " = 1
  ) |> 
  janitor::clean_names()
tasmania
```

```{r}
tasmania |> 
  autoplot(takings, color ="darkviolet", size = 1.5)

```

We see that the Takings have an upward \*trend, yearly \*\*seasonality\*, and an increasing variance. We can try using a log

```{r}
tasmania |> 
  autoplot(log(takings), color ="darkviolet", size = 1.5)
```

```{r}
tasmania |> 
  gg_season(log(takings))
tasmania |> 
  gg_subseries(log(takings))
```

```{r}
tasmania |> 
  gg_tsdisplay(log(takings),plot_type = "auto")
```

```{r}
stocks <- c("MCK","META","NVDA")

?tq_get
stocks_data <- tq_get(
  x=stocks,
  get= "stock.prices",
  from= "2010-01-01",
  to="2024-01-25"
)
stocks_data
stocks_data |> 
  distinct(symbol)

stocks_data <- stocks_data |> 
  as_tsibble(index=date,key=symbol)
stocks_data
```

```{r}
stocks_data |> 
  ggplot(aes(x=date, y=close,color=symbol))+
  theme_dark()+
  geom_line()


```

```{r}
#| warning: false
stocks_data |> 
  ggplot(aes(x=date,open=open , high=high, low=low,close=close))+
  theme_dark()+
  geom_candlestick()+
  facet_wrap(~symbol, ncol=2)

```

```{r}
data("JohnsonJohnson")
autoplot(JohnsonJohnson)+
  ggtitle("Ventas")
```

```{r}

us_retail_employment <- us_employment %>%
  filter(year(Month) >= 1990, Title == "Retail Trade") %>%
  select(-Series_ID)

us_retail_employment


```

```{r}
us_retail_employment %>%
  autoplot(Employed) +
  xlab("Year") + ylab("Persons (thousands)") +
  ggtitle("Total employment in US retail")



```

```{r}
dcmp <- us_retail_employment %>%
  model(Descomposicion = STL(Employed))

components(dcmp)
```

```{r}


us_retail_employment %>%
  autoplot(Employed, color='gray') +
  autolayer(components(dcmp), trend, color='red') +
  xlab("Year") + ylab("Persons (thousands)") +
  ggtitle("Total employment in US retail")



```

```{r}
library (tidyverse)
library(fpp3)


empleo_tsbl <- us_employment |> 
  filter(year(Month) >= 1990, Title == "Retail Trade") |> 
  select(-Series_ID)

empleo_tsbl |> 
  write_csv("datos/empleo_eeuu.csv") 
```

```{r}

empleo_decomp <- empleo_tsbl |> 
  model(
    clasica=classical_decomposition(Employed,
                                    type="additive")
  )
empleo_decomp

```

```{r}
empleo_components <- empleo_decomp |> 
  components()
empleo_components

empleo_components |> 
  autoplot()
```

```{r}
us_employment %>%
  model(STL(Employed ~ trend(window=7) + season(window= 'periodic'), 
    robust = TRUE)) %>%
  components() %>%
autoplot()

```

```{r}

empleo_stl <- empleo_tsbl |> 
  model(
    stl=STL(Employed),
    stl2=STL(Employed ~ trend(window=7) + season(window="periodic"))
  )
empleo_stl |> 
  components() |> 
  autoplot()




```
